### PR TITLE
Fix bitcoinconsensus.h

### PR DESCRIPTION
**Pull request by phelixbtc**
Hopefully fixes https://github.com/namecoin/namecoin-core/issues/40
Only tested on Windows so far!

### CODE REVIEW

**Comment by domob1812** [comment]
Untested ACK.  Feel free to merge given that it still compiles and works.

**Comment by phelixbtc** [comment]
Merging. I guess it will show soon enough if Linux people run into trouble :)

**Comment by unsystemizer** [comment]
I tested, no problem building, installing and running on Debian 8 which also has Bitcoin Core 0.11.

**Comment by phelixbtc** [comment]
Great, thanks!

**Pull request merged**
