### PR TITLE
[Mining] add rpc commands: “createauxblock” and “submitauxblock”

### PR DESCRIPTION
**Pull request by bitkevin**
Add new aux mining rpc commands: `createauxblock` and `submitauxblock`.

* Separate create and submit AUX block, make it clear and more readable, instead mixing them in one rpc call command `getauxblock`.
* With `createauxblock`, miners must specify a namecoin address as the coinbase output address instead of create random address using build-in wallet.
  * so we can build `namecoind` without wallet: `./configure --disable-wallet`
* using `getauxblock` is the same as before, it's compatible.

Original PR: https://github.com/namecoin/namecoin-core/pull/159

### CODE REVIEW

**Comment by domob1812** [comment]
Thanks a lot, looks good!  Please just remove the name tests from the test_runner script, they do not belong there.

Also, I don't quite like the amount of code duplication between the two Python tests - I'm pretty sure that one can restructure the tests in a way to not have this much duplicated code.  But I can do this myself, and don't want to bother you further with this. :)  (But of course feel free to work on it yourself if you feel like it.)

**Comment by bitkevin** [comment]
@domob1812 thanks, fell free to reconstruct these code.

**Comment by bitkevin** [comment]
I have mined few blocks using this patch: 
https://namecha.in/address/N59bssPo1MbK3khwPELTEomyzYbHLb59uY

* https://namecha.in/block/340416
* https://namecha.in/block/340420
* https://namecha.in/block/340425

**Comment by domob1812** [comment]
Please rebase a PR instead of merging upstream changes, so that the commit history stays clean.  Also note that the merge effectively reverted 838df256562007bfc813eccaf06c87c1404e398f.  I'll manually integrate your commits from this PR, and merge them together with a simplification of the Python test.

**Comment by domob1812** [comment]
Merged via https://github.com/namecoin/namecoin-core/commit/7a35436d0c92cf98853fbb91bdbbe4c5dd11df89 as described.  Closing this PR.

**Pull request closed without merging**
