### PR TITLE
Gitian descriptor for macOS - renamed from bitcoin to namecoin

### PR DESCRIPTION
**Pull request by jonasbits**

### CODE REVIEW

**Comment by jonasbits** [comment]
not tested yet, plan to test

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

utACK 5255c9250c4398b1deb5b4d31555fd74e7379369.  macOS Gitian builds
are completely broken in dev branch at the moment, and this PR
shouldn't make it any worse, so I support merging without requiring
testing.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJY9YKVAAoJELPy0WV4bWVwXqsP/imKrVU+1t83c15iSepTkPz1
Vn2VnAT0N4dIMqK+ITDuJgSL6P+UBH3Ay2ue0bI+e/uYyFHd7V+9QryIjaKJdZPx
wP6+Nz0LSfBG8bYjehvABOeqSzmEQ1yM4b80CETd+iM5TLpOgISg6+X7cwloIeyx
GNnISOOjBWLWuNQFPY5h3Ss9WIMS3kvQWgjRXGg1sFWV9msUFzh5/rtuSXbMklMc
ixdjH6CAaRIr+2uAVIruBl1NWnvYOrceI4YTOZmULiQqVeoFceGBwwas2FxcQtx+
ln5nr13e1BeduCUIr+reJHUyvU4BnMk2A/6Ynt9zVTDakRl995V86u9QfQHnM3VP
XymG/gVqNNg7n3CbT7XrMhyAxy2lIZjYcVvPdLJqX8rOii9qwzomXLa9w+bdxwbc
xdz0upnxosQMejY1IunkTxYicMVXQ+nxoll+KAMNpzPiJRIekW+XwMB2J3vHvKFd
qwJZFyP1CGidYtJlPqX4X7/qRSI5eFPwyRBBvVvYSjDv1Re9XcLAsa3FyYxUL17o
/+PdESWv+9+Qe+7LlL7uiReDhjbh5WlgIyvejttefNt7DCxBi0zlRgO4w/b0Qmv7
K71kXXanbGkjusDUbuafjio+o1xcC7B5FldzR7aRYLmQWkhtFpasHcZhjm9RzYOt
5+LPvnvqg0VFVQmneEFJ
=Dwga
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
@domob1812 is anything blocking merging this?

**Comment by domob1812** [comment]
Nothing except that I don't know anything about Gitian - but for me, 5255c9250c4398b1deb5b4d31555fd74e7379369 looks good.  utACK.

Feel free to merge - or let me know if you are not able to do so and I should do it.

**Pull request merged**
