### PR TITLE
update icon

### PR DESCRIPTION
**Pull request by fsb4000**
fix https://github.com/namecoin/namecoin-core/issues/56
Sorry, my fault with low res.
I didn't open bitcoin.ico and just saw properties 
http://i.imgur.com/rNTd0zO.png
But bitcoin.ico is multilayered ico file.
I changed namecoin icon so for now namecoin icon is multilayered ico file too,
It has 7 layers:
256x256
128x128
64x64
48x48
32x32
24x24
16x16

### CODE REVIEW

**Comment by JeremyRand** [comment]
Concept ACK.  I won't be able to test this until my main computer is
repaired.  Thanks for figuring this out @fsb4000, I had no idea that .ico
files could be multilayered.  :)

**Comment by fsb4000** [comment]
@JeremyRand You're welcome. If you open ico file in GIMP you see all layers. I use GIMP 2.8.14 for the creation of this icon

**Comment by JeremyRand** [comment]
Just noting that I haven't forgotten about this PR; I just find it easier to test after Windows Gitian builds get merged to master, which will hopefully be soon.  (We're waiting on upstream Bitcoin Core to merge something first.)  Once Windows Gitian builds get merged to master, I'll finish testing this PR.

**Comment by JeremyRand** [comment]
Actually I got impatient waiting for Windows Gitian builds to get merged to master, so I constructed a temporary branch where I could test this.  The branch I tested is at https://github.com/JeremyRand/namecoin-core/tree/temp-master-gitian-windows-nsis-tarname-namecoin-fix-win-icon-res .

Anyway, I confirm that this works as expected, so ACK.  Thanks for your patience @fsb4000 .  @domob1812 if you agree that this can be merged, feel free to do so.  If no NACKs are received in 48 hours, I'll merge.

Once this is merged, it would be awesome to backport this to the 0.12 branch as well.

**Comment by JeremyRand** [comment]
Merging this, hope I'm not stepping on anyone's toes.

**Pull request merged**
