### PR TITLE
Enable #namecoin-dev notification on travis-ci build failure

### PR DESCRIPTION
**Pull request by josephbisch**
Fixes namecoin/meta#20.

Didn't actually setup Travis-CI and test this, but it should work according to the documentation.

### CODE REVIEW

**Comment by josephbisch** [comment]
@domob1812 - Can you take a look at this when you get the chance?

**Comment by domob1812** [comment]
This is more for @JeremyRand, he's been doing the Travis-CI stuff.  I honestly don't have much knowledge about how it works.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I give this PR an untested ACK.  In the event that it doesn't work as
intended, the impact should be minimal (it shouldn't affect the code,
it just might make Travis complain until it's reverted).  @Daniel if
you want me to test it first, I can possibly do that, but I'm pretty
busy this week and might not get to it quickly.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWEW4gAAoJEAHN/EbZ1y06iWMQAJXcwtUBg2OhbRHYWEKUwppi
eWQvykZTzSMhEfiUxaup+KkFpaXNNtchgfPOUfjpb05qJIbV1gSEiXGtn0etGJAr
vcf/9PJznHwFAE/Z5J7PmOsA4QDBgxk6ImOujwUOveTepDz7QCSmpp2E9BHz1q2k
b7W+CrLnFNapabNtgOi7rLoqI6oR0akZJnufykGsfDLBxrviJCBL9C3m0uJYbLrr
LvnLDhHkK+mzRGHX+JR8Dw5vw+nFN8VNTyD+HA/msTveoOHnr98fUuZ2hdz7tIKu
KJSpB6pFiymFDpWtpeeBCnHRy8QPkJp0UYQd26RQzIADOBh+dG2jiWmXOUDv3RPA
DDQifqWLT8vdokxz8+RnGHS0QJJm030P0L5AM7laz4sOVUVkitcQUsI5Pdq6ZulH
S7UQLRbQl4JE8UVMDTPkivK/Jp+OU+rUea63bRnhNfJVBziI5evEveRmSiy0LtPG
CW16saFQ7KsK4XkRdiUOmG8I0TAXc8GNjPm2VjjBHqt5l+8PvdpkDauMonQDXgaZ
RoXf4Zz5xUDQslIS0UMpEmPcxlkUWUuS+1Xroz1071kCwnuLYLXv0+9FcUqyKOUR
q4PsHaK8v7T2ZRK5nZ7cwcHFz0fZ/Ox/nGS+k9VUkU1u/Y4iGW7feaO2iAs/ZRfL
9JueMuGPaE2G9263E744
=2xE7
-----END PGP SIGNATURE-----

**Comment by josephbisch** [comment]
@domob1812 (@JeremyRand specified the wrong Daniel there)

I can test it instead of Jeremy by setting up Travis on my fork, if you want someone to test it.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Oh, didn't notice that GitHub applies name tags to emailed messages.
Apologies to whoever I tagged there.  :)
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWEYFvAAoJEAHN/EbZ1y06qrQQAJ/1Oii/Gt9Qh0Wq9y6dqBtX
4jr9DSmDcw5RjftN5OCCPIfnt4/E4sWYnykOh0Lz5GA6lenG+9UDgqPrIhdhhlcj
rbGMGfGBBL22Fk8N7Zafxtp2nRoMb/krVqoZsfiulbLSnbHB+1zw1055PtlTIoCm
K/8FDzGL7UH14pHbSzrZtpCoWKbnFZn7g4DrMCbejI2NpEWHZrUewG0oLjHavzPn
VSJif/yGnruGTLAHbpNbIQ3Rsipdjqcm/cO1qFjNJIzcIXi0OmF15QCGemnn/Xcc
Qb8T9UU+wMfjLzdksaorBsTgrGHuVRApHgxnhio+qupc4jbrAmenABjjFoYDIt3M
NuSJdNI6hrAIqux2ZAmyPZ+55tIAlfD07T1yhLxSwFGy3WAFXjGKj/zGe2dVz6TF
nhQZefuh8h3u8Pa8wDaFjCLLcKUmtirJgbm10SOACJA/OB2Xis6XL71PY5nX8b/y
MDN8xkIOWHAwylJpeMtalZzeoEQGsyMw4Cyl0JyUPfmB3h62ra3dPagclY2uHNbI
Y6HTivy7CpIj014kE56XpUy7vZ4O5gVVKjeyten/w/q6BCfdAWaTK1K+DuZz8/LW
CdqCXNAOq40pU4sjoULT/CBN3c3O7hYychxUJcbDYd/l1eX1ZQR29p3vu3rG7sGl
N+yquHwHjw4TVaSkWWxg
=t7f3
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
@domob1812 Would you like to merge this or should I test it first?  AFAICT if it fails, it won't hurt anything, it'll just make Travis complain until we fix it.

**Comment by domob1812** [comment]
ACK.

**Pull request merged**
