### PR TITLE
Update nodes_main.txt

### PR DESCRIPTION
**Pull request by mdavids**
Update nodes_main.txt + chainparamsseeds.h with IPv6 address 2a00:d78::712:94:198:159:7 (equivalent of 94.198.159.7 alreasy present)

### CODE REVIEW

**Comment by domob1812** [comment]
Can you give some explanation of this?  Where did you get the new address from?  Why do you think we should add this node in particular?

Also, please update `chainparamsseeds.h` accordingly as well (using `generate-seeds.py`).

**Comment by mdavids** [comment]
This is the IPv6 equivalent of 94.198.159.7, that I run and that somehow ended up in this file.
Since that node was here, I figured it would make sense to add it's IPv6 address too, especially since there aren't that many. Forgive me if I cut too much corners here, I am not exactly sure what the proper process is.

**Comment by domob1812** [comment]
No worries, thanks for the explanation!  That makes sense, IMHO.  Can you please push the change to `chainparamsseeds.h` from #283 to this PR instead and make it one commit (that updates both files together)?  Then I think we can merge this.

**Comment by mdavids** [comment]
Squashed: https://github.com/namecoin/namecoin-core/pull/282/commits/f502ef361224af77a457daac1678b4d92a91f48e as per request.

**Comment by domob1812** [comment]
utACK f502ef361224af77a457daac1678b4d92a91f48e.

**Comment by JeremyRand** [comment]
Concept NACK.  These files are supposed to be updated via https://github.com/namecoin/namecoin-core/tree/master/contrib/seeds , not via individual node owners submitting PR's.  It is a security risk to permit individual node owners to directly influence the seed list.

**Pull request closed without merging**
