### PR TITLE
Add contributed seed node.

### PR DESCRIPTION
**Pull request by domob1812**
The node is run by redblade7.

### CODE REVIEW

**Comment by domob1812** [comment]
If there are no NACK's in the next couple of days, I'll merge this to `dev` and `dev-0.14`.

**Comment by redblade7** [comment]
The IPs in this commit are correct.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Daniel Kraft:
> If there are no NACK's in the next couple of days, I'll merge this 
> to `dev` and `dev-0.14`.

I'm traveling until Sunday evening and will have unpredictable ability
to review things.  If there's not a strong reason to merge quickly, I
request that merging be delayed until, say, Tuesday, so that I can
review.  (If there is a strong reason to merge quickly that I'm
unaware of, then you have discretion to do whatever's appropriate.)

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJY3YCOAAoJELPy0WV4bWVw0HcP/1oSZIokd+mibyhoV4AED1VP
JKnry1ufvHk6ioU5qNaspZGkJrp9PAJvMVefZ/vb4+tvkHcOw1wsqCFO0Zzlt0tG
q7lCW4wsmGhNPaBI9Etlr+sLtT6FGkoC5/0aB88iikW/o0ofy1nIgXoHRPfPcp4g
Q8cx28rW2iN+b/WKhKNx0s9M8rxH3eYheWfAq/o1mKTBRWqbGVJeYYXRbEVN6hb+
v9tRlIW17lIlVUlsFvCGavtI6bptFxFdqoEVfY7oZ3kTIjBCHH5bWitPNe4IuiH6
nB6S7oKQ9SjhwmqKLSVhaqkHFyGVU/fmVGWg3YyjM53B+0Pt4yA5DorhMyLDIU+X
B7z4AK0ZfTPutfhLvznH8uweRfJu6+F6ZLfBog0wj38RmIK1XIwua3AWMyDywtoA
/qIrC+p+h5M2i4Da13IaPoIQtORwJUenliSBjNgiLlEmJNfl+ZVin7BEdYbWTAL2
+NolWUaiBF9Qm00xPf0w0R9Jrmp4FfVn2rzLtI9+nqxQHoHHzJigyLi9m7zWccay
wcOigfKeZbe1xtQTrs6ehWAb6AUXmrBjAdtS/97gQRjz8zyWvTQV81oRbmgYKG0P
CpSRPtqamTmC6MmCGruXbN3u9NtQrkg+lJnn1qwh/BGUuRXVXrJPo9Ln9x4aJP6z
ySZdrUFOfX/KV1gxeZqj
=gFbg
-----END PGP SIGNATURE-----

**Comment by domob1812** [comment]
Sure, no problem - this is not urgent, so I'll wait until you had time to review and ACK.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Why are we manually adding nodes to the seed list?  AFAICT there's a
specific procedure for this in the release process, see
https://github.com/namecoin/namecoin-core/tree/dev/contrib/seeds and
https://github.com/namecoin/namecoin-core/blob/master/doc/release-proces
s.md#release-process
.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJY5tRBAAoJELPy0WV4bWVwvQgP/3li9RpwUuNnBL3MFz129tt5
It0OzAwbocGS87LzihrfGXuqHQaU3YOAzMN+cWG58leFmAmv4FEFrHawXtLOzeH3
4IviiomUAFd82kJ2rLS2T5iPUrBJtXreOKW181kUrctLPofLTr360qfZEfaCLnru
TM57dcBrmShZX+lY/3I5u/fIQsjEFv6T161WDW6ge4b7LRDNRyaEUI3zsOESvlWA
6sDFN/Bxl6hf3qURvim2lTmqxBJmgcZEf7boWNk3JErK5+gdWA7wk7XxXGFUcTWs
lU0UiBUqibiQ3DhKVuYjllhZ0EdqLGeyufSI3Lzb42EsiEtr7r/9/WgvqoL/paWZ
umX2drjgsASMdwgKWSp/QK9YYhjqA0zHMlVHKX6B67X5vVw6muPbPB+8qbI9Alv/
8Wim14BQ5VXFymPLTh8ibO2q+AbB9Bd5xnia5HPbDtQoe+KHDuvfR3UVT8YDrPS1
d5grcsZfTJj5BDqDclaaxIqsWcuiArGiJ+8HpY7FTWVcvDB+c6O+NsPf2yQkZFgE
ajQSsL5+g/jbyGN6CxO7dgHIz+yk2VzHSzKAr8U+Pu88iMa2OAlfIwOEwm2cK6oj
b8iMGE5C6esCSgsVvxyBcfZ/wZLYqOz86ZeCDMkQE8KpsDwAjKFZvroMDC/kfB3A
J9UMOT0vkUAbnUypqFGL
=Q4Ih
-----END PGP SIGNATURE-----

**Comment by domob1812** [comment]
This process just updates the list from a DNS seed.  AFAIK there's no way with it to specify particular nodes that you want to have in the list.

Of course we could follow the same process, but that would a) not allow us to accept direct node "contributions" like this one, and b) need to have well functioning DNS seeds in the first place to pull nodes from.

So I think for now it is best to just manually add nodes.

**Comment by JeremyRand** [comment]
Daniel Kraft:
> This process just updates the list from a DNS seed.  AFAIK there's no way with it to specify particular nodes that you want to have in the list.

It appears that Luke Dashjr doesn't think it's a good idea to bias the
seed node list towards nodes that have asked to be listed.  See
https://github.com/bitcoin/bitcoin/pull/7415#issuecomment-175335402 .

> Of course we could follow the same process, but that would a) not allow us to accept direct node "contributions" like this one, and b) need to have well functioning DNS seeds in the first place to pull nodes from.

nmc.seed.quisquis.de appears to be functioning fine as long as it's not
accessed over Tor.  I can ask Peter Conrad (the owner of that DNS seed)
to provide a seeds.txt dump if you like.

**Comment by JeremyRand** [comment]
Hi @pmconrad ,

Is your Namecoin DNS seed using a Namecoin fork of sipa's
bitcoin-seeder?  If so, I believe it should be producing a file called
"dnsseed.dump".  Any chance you could make that file publicly available
over HTTPS?  Updated periodically e.g. on a cronjob is fine, it doesn't
have to be real-time.

If that's not feasible short-term, let me know and we'll figure out what
to do in the meantime.

Cheers!

**Comment by domob1812** [comment]
Sure, if you prefer, feel free to close this PR.  (But I thought you referred redblade7 to me for contributing the seed node.)

**Comment by pmconrad** [comment]
https://bitcoin.quisquis.de/dl/nmc-dnsseed.dump

Updates hourly.

**Pull request closed without merging**
