### PR TITLE
Show `.bit` form for `d/` names in `TransactionRecord`

### PR DESCRIPTION
**Pull request by JeremyRand**
domob: Added dummy description to make the merging script work.

### CODE REVIEW

**Comment by JeremyRand** [comment]
Tested; works fine.

**Comment by thesquatter** [comment]
Don't. Another namespace may use .bit tld.

**Comment by JeremyRand** [comment]
@domob1812 This is ready for review.

**Review by domob1812 — COMMENTED** [review]
ACK.  Please squash the commits, then this is ready to merge.

**Comment by domob1812** [comment]
Thanks!  ACK f5b20514e99f122787b8edb943bd276b72783e10.

**Pull request merged**
