### PR TITLE
Reenable getblocktemplate for Namecoin.

### PR DESCRIPTION
**Pull request by domob1812**
This has been requested by miners.  Note that merge-mining with GBT means that the auxpow must be added to the block manually, as well as setting nVersion accordingly.

See the discussion in https://github.com/namecoin/namecoin-core/issues/98.

This PR is created against the `0.13` branch, since I assume this is most useful for miners and testing.  I will port it also to `master` and `dev` if miners confirm this works and is what they need.

### CODE REVIEW

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

@DrHaribo Can you confirm that this PR works for you?
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYZvAOAAoJELPy0WV4bWVwp1MQAMVg8lZFQ2gT7Wz9uVWjgNOs
t6ddxjMGNr4wEd7ki0AI3D3GfYEftI41BqmZICq6u4gn9GyMTYwnYPLI7vFO/ap2
xsloO+fMWDv/COjw9sVeKgiMGJCuh/ljbpaN/dA1v3nF+pTOaObx78aL1Tpjtl9M
JfWWwcWDxB1RGTQL6O1dDQMqCyxthsR3VUwT0bdNG1BmPzCbpMUBjVk5z7wChMkG
laCw9cYGUVQeKyEVscp8p3BoMP1bRy9AHXtoCPr1iTdSIlIsQeFyJJCf4hphGeVe
uT/rXnjk49YU4B54nx4XWgKIcMkf4T/B5FM7kNskHTKaaEIAXLBRVU9ki7sFvn2q
gfkkA6iEyMH/47kuqHvQakxHFTNOS+6j/gBv1oGOVxPCA+TZtaFxcJJ2632GzJPK
2D8j9kiWESujHq8ToczgggNwzSc89LtxqcQmEVEyz1LxtRzW28wM7pp1mGqHIVaC
feu4Teofy9GED2ZzkNq+SXg1b923WKU+ySBewzkGvecGj9IgMtcUAeN2n+cZspvL
XzRpBWAT0/NNK7I3+gIPEWPDzLXlIcimEZDJEm+iSN4B50pI0lOAmBOJPLULemcS
kvi+rxzkIKzKsNQB1cXKp1h7JgFqRXvWjazWaJZ8Ilz8CSm1FzVURtBrEyeUShFn
2aqIn5InAZopXl3/K936
=fYqc
-----END PGP SIGNATURE-----

**Comment by DrHaribo** [comment]
Yeah, works for me.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Geir Harald Hansen:
> Yeah, works for me.

Excellent.  @domob1812, feel free to merge and port to the dev and
master branches.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYaMw5AAoJELPy0WV4bWVwz3wP/3/jM52+OYrYuKxpyxRaxlin
df5Ev24osKvKVk5tZIIGNdTTZ4vzb3VISi6jQ93YohRvrApH404MkWWa926QHBDn
xHv8krLEf7jsgKSJ85yI0Hekl+CsyldqLeOJtiOYbDJAAJCJ/JTZ0gWnldFTZDVE
bGIu5GjAqLWVZyDfkNE6TJ0MCqDktJPToCp31UZkb5sQNdTRH4VsAQU1FNjeqqSk
kQyE2KkDj5ofbKRtUjbyzqGg7Kslo5J6UUkA2NNdrDTzeeMZp3qvUu6tT+QrDdOH
W1AK4NMNKFa3t8g0VpzfL5MGbkBQfYS6XIhUllaNAy/mMKeBdrnEfMu+x/Z9tp1Y
nQsvUtUtvsqLJydKIqP9GX8dS3bxodHNzN+U/oFRbiatOnI/3C48/AR+DL+jbpga
59UxVnOIV6obSH3DuAn53e/l2WYYzdHC1f7VDtxh4UU9VkzwkGwqyBvzjtHUefOt
je7X1JviLw3yocbgZ3HThyG8lhh/ygnCuHauGKRfyQBtOZ5cv56MBL8g6FmT/WPP
q+qeNK3L99kNhvvI91ZSJzgTMq+smdtlntf+QSwO+fCxymsj4mgh6xDUuPBnlLnm
oqkbob5SkfB91XctC/cg70Q+VEacvWP0vMyfQ3qAVe0SP2dWOloER7T3u0lU20hO
hJrTscdSq8XmPaXGfnnq
=tJCr
-----END PGP SIGNATURE-----

**Comment by domob1812** [comment]
Merged via `auxpow` and `auxpow-0.13` to `dev` and `0.13`, respectively, and directly to `master`.

**Pull request closed without merging**
