### PR TITLE
Name decoration in Qt GUI

### PR DESCRIPTION
**Pull request by JeremyRand**
This PR adds the appropriate decoration to name operations in the Overview and Transactions tabs.

### CODE REVIEW

**Comment by JeremyRand** [comment]
The name decoration code from @brandonrobertz differed from that of Mikhail, in that Brandon's included the address while Mikhail's did not.  My perception is that the address was distracting (especially since it caused the name to frequently get clipped unless the window was very large), and most users do not need to see which of their addresses was automatically used for a name operation.  So, I'm excluding the address from the decoration as Mikhail did.  If anyone (Brandon or anyone else) thinks I'm making a mistake here, feel free to try to convince me.  :)

**Comment by JeremyRand** [comment]
@randy-waterhouse You may be interested in reviewing this.

**Comment by brandonrobertz** [comment]
> The name decoration code from @brandonrobertz differed from that of Mikhail, in that Brandon's included the address while Mikhail's did not. My perception is that the address was distracting (especially since it caused the name to frequently get clipped unless the window was very large), and most users do not need to see which of their addresses was automatically used for a name operation. So, I'm excluding the address from the decoration as Mikhail did. If anyone (Brandon or anyone else) thinks I'm making a mistake here, feel free to try to convince me. :)

Removing that stuff is all good in my book ... I don't remember why I added that TBH. It could have been for debugging some of the old wallet tx-based code. Nice progress with this!

**Comment by JeremyRand** [comment]
Sounds good, thanks @brandonrobertz .

@domob1812 This PR is ready for review.

**Comment by domob1812** [comment]
ACK a80e13352e94861f69182f65b9996301cd84fc5d from my point of view (without knowing too much about Qt).  I'm not merging right away as I'm not sure you are fully ready, but I'm happy to merge once you confirm.

**Comment by JeremyRand** [comment]
@domob1812 I think this is fine to merge in its current state.  There are a few TODOs in the source (e.g. moving the name script loop into a convenience function, and using more friendly labels), but I think they can be done in subsequent PR's.

**Comment by randy-waterhouse** [comment]
> @randy-waterhouse You may be interested in reviewing this.

I would be but unfortunately some of the upstream dependencies have now been upgraded beyond the OS on my build system, e.g. unrecognized command line option ‘-std=c++17’ building boost boost_1_71_0. I'll get back to you when/if I ever upgrade again.

**Comment by JeremyRand** [comment]
No worries, thanks @randy-waterhouse.

**Comment by JeremyRand** [comment]
@randy-waterhouse, I'm curious, would it be helpful (going forward) if we made Cirrus CI upload binaries of PR's?  I suspect this would be pretty easy.  Obviously this would involve trusting Cirrus infrastructure, so the binaries shouldn't be used with any critical mainnet wallets, but it might be good enough for QA testing of PR's.  Let me know whether it's something I should look into.

**Pull request merged**
