### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by khaledJabr**

### CODE REVIEW

**Comment by khaledJabr** [comment]
@JeremyRand  done!

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

And another error:

https://travis-ci.org/namecoin/namecoin-core/jobs/173146878#L255

Can you paste here the "apt-get install" line that csbuild generated
to install csbuild?  I suspect that I know a way to fix this error,
but glancing at the csbuild-generated apt-get line would be useful.
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYG/tcAAoJELPy0WV4bWVw2ksQAMGaluJn1sLLClJhIcvXSf4t
JUhBxdGhjUBABKcg3+Vt7KhVsC4ZQ+XHQ9nWtLcFxvC/HvcnZv4DW4/bX5aUTMin
+SpK2Ux+dAvwTTphfkELNs876fYHD8YBgBZmAq3rF3I3XcJIA6Zq10iixVvAeWlv
j4qpthpuxSTMWId0GwJ1rj9TDKlxbG4UJAqBkc0ei0q1jkUrTHQQLoiT2XdiRvgz
l15aEQGc6zqJoPRrxUENSINUT6QRC2z/8BmNXxZG9HjD+fag1WhtW0rY+MHM1dg7
BqVBYBq+vVMP7U7HbXQLHQsQ/NER6UFS8sBhKuKWUu5QKtyavM9Le5KgwoaqAOG5
mzMWhtNBWDLRQi9v0XJlqhZhJtiTZXCNm1fMIY6boQPnnnDIM/VaBGASYTZzd3hq
hy1yZR2bHjOtXME5yc2+fyE78qusSKiNaAeMaZFfFJoUH887jEG18RyhaV/3nuAJ
voBCJangKan1xeVo8/5xbRCCSH5HQvBpHMK8LmnahzToSJV3N0joEuQut1WgTs7E
4oRT/OuIfWlkUQY09h5QpVF6Ch5Esy6cz8g5b6kBwKwFiNsMhLoUGOwGtQ2uuxPQ
ytUC3DPKSy8M69dHxeEtKqBF/rNHO2Y2BYOmqQgaiFB6oNr0aUYlya9Zl/4wIA0m
US5UsxWPY/rMgGHLXfM7
=lPsZ
-----END PGP SIGNATURE-----

**Comment by khaledJabr** [comment]
@JeremyRand  here : 

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq apt-transport-https
    - echo "deb https://kdudka.fedorapeople.org/csbuild precise contrib" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq -y --force-yes csbuild
    - sudo apt-get install libtool

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Okay, so what I think would make the most sense is to remove csbuild
from PACKAGES, and add a line at the end of the "install:" list,
something like this:

- - if [ "$STATIC_ANALYSIS" = 1 ]; then travis_retry sudo apt-get
install -qq -y --force-yes csbuild; fi

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYHADrAAoJELPy0WV4bWVwk0AP/2+e+k9eySCnGzywHpvZVD/e
SkJRUbZuS8hc5unTPvVy1oNs8Fx7+lKJhs2fpIRAHA6b/h/S5TjTJG16CiXRfRiV
DNepVnIiLb+IOjzaqPKx4oJSdE2AY5MLAZ0G45Ca5AlzMwp8M3OFkYDC+9WCuwj/
aG2F0s3tFYmXk0MTwh6MKs+qL5P1cuCiWYt1Ii399Lw7xZ8I2+G/Sy6s8BiOIPGq
UlDBoTPkFDh7IXMffWaPDPmp5t7gItgn8KQd76825I84f/jBPcviF+tcZJXqk07F
VFxztPT0NOFKWRCcO692F8fiuAWU9yvZL/47miyvBwTd/4R4E6oD5BHGhCQ7azfx
pxt9pgfdFotzcaGFtqQ9mpH7e0FTYBcIg58yhV7egYTaJhSk1TxIF0HNAkrc3vW6
QeFrkU2Xzf3MbhUWq/QT/1g/qkf3tfEs4HB2R68eJKmxthKHWI9Uv+zRMCQ5bVc7
T3u5jwbOssS5tFn2c7aNj12z+7Z+Jw9rmtsVsfCOPwIxPy8WBpjElfOzaZ+wensB
fsLnB9v7I4ZeAyi10Zk3/3p1fVk4wibSfdsgHr1Y2A1AQaihdlbbm0xYjaRGL3te
5Fa0X/r6tbeY0FIT61LryXr0AtBAEKlIy+swt6yN15XSAXjb+QWIvCf3jfTcHfYq
NEMYz+oi/yAi6Ir7t4Kx
=kEuh
-----END PGP SIGNATURE-----

**Comment by khaledJabr** [comment]
@JeremyRand  I made the change, i hope it works like that.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Try swapping the order of line 50
https://github.com/khaledJabr/namecoin-core/blob/5b8bd64eda355f6f701c566
5856d90e23979cb16/.travis.yml#L50
and line 51
https://github.com/khaledJabr/namecoin-core/blob/5b8bd64eda355f6f701c566
5856d90e23979cb16/.travis.yml#L51
.
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYHAT0AAoJELPy0WV4bWVwtsgP/3QSiHkl0XoZDf2HP1FHSrDJ
uTbyGxVkaOzIgK+YLCn8XCpbkvtFlmTF394uHktXZYNIoPHaVruJj+FcSb7Pd/vJ
e05P+uh21xREG9olmbAzXbrjEPO/4TetRP/1/QYN5XCYvuIq23HISXmzO/8OzViE
ljulwA65dKNKl1AyxwSDI6DiwQjMMnNUICgEj2k04RMN9G8JhthRnJxtFwRf60bg
xm2Jg1Jdu7QTTSmK8CNuNbwGiSei/lhWfBVUr/gb+Ex4O6M3KPs0BYeqWPoQRU+i
0oxo7NQTKvw0OpbfDotO84cpIVEAPWBsoUVza5M57/e4B52h0touUbHaB7dXMpFv
3+ChsIgrusfH00jmxwasEp5cA9CjKSemBc4DcpvTpkZ8nU/K3T3+qX94rE6F8Swu
xQIWQq4DdYKAJFBch7uRPSyFzaoHH0JT8f1ixQ1pQ7kIfb7oX6iWFriMP+beQPoN
OTmSenkkqEj2a+y/hIlmtkyrmgsllRWINZo2sYXE5X2ER1z3B2gG4PfW8+fdH2yU
H6vI1nTBUEZytz+RIuuUW9YUrAkgRWgAziwQb+SIg5rlQb6pw1jlteDiIDKP2du6
yvuwmd+UHVmg42aO2NByx9uVV+7OSrEm9CPpj+o9fhCFVP0PuuWVzhcTmC7ASs9E
sZdmEpA3WnjQHItPSGDS
=/HVs
-----END PGP SIGNATURE-----

**Comment by khaledJabr** [comment]
@JeremyRand  Done!

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hmm, interesting.  We're definitely making progress.  Looks like
Travis doesn't fetch the bitcoin branch by default.  Try adding
something like this, right before line 76
https://github.com/khaledJabr/namecoin-core/blob/9a6c6f124e5380f4e3fecc9
222d251971f581165/.travis.yml#L76
:

- - if [ "$STATIC_ANALYSIS" = 1 ]; then git fetch origin
+bitcoin:bitcoin; fi

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYHAufAAoJELPy0WV4bWVwm3gQANhteiW8vAZxh5/NUDwLSa/7
FD9jaF2lK7J0DnJb32hqxPzM6DPjBTY4z474FDMFU7ZI6pH15Y3HQt5ELy2esfN9
LIXrHyoLayHlKM0mQTWGfb1hQZsynlNiLE6sGYaCvyM9YyWj+NmsPmuzYZWFm1XR
MKfJsNmjgG+pmrsfafTuAqtHfvRrfT1ljC3AOq6poRmN4chASfUDXYHP5roqyE0H
aGt0CD8P8CnhKUU3Z4qnpyn3/8vTC8BIWKM+CuovHWEezQ0BAoTZFZtCUC5vwcqt
bxgTQeqvNhq3BoVRl+n5IevDLeG6IQA1QESArJ5gKoUNMyNbrMOkSPZqyPewvjtf
fOFJXia1a6ZUdjzGUb3ScBp29OAv/eBE/V06cS9turr5BoXw2MwPbjAl7IHeH6FQ
lH/UHQiouGsjbYyJlLOD4SUTePf+tqnOLb+mnGmmTMWw7tvfTgA91ORlfQvpx2w0
ntXzrJH13ExLCIPtAOCWfWFYnrlCYCMlDVwD1PFCAZzA1qx9DfbPLbnG8Ikb2naE
99Kq63dyJVku1lqjJcEfKG1Efc4HRPTwPXrfrJLwgTZEI8Q4PgmwIuIsPieYVY+1
UdGAIcECHjW8Or2T7WW8vG2/7/gTOCM5m888IgrRjYbG0NnFOWWfPtZpOoIVg1PL
kZs88BhQfUAI08PGQWaa
=AM+2
-----END PGP SIGNATURE-----

**Comment by khaledJabr** [comment]
@JeremyRand made it

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

There should be a space between "origin" and the plus.
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYHCUwAAoJELPy0WV4bWVwMkwP/jMsS4Qj7CgNRqbuSN47Hq3y
VBq6IQ8kfnpitIJnlQAsJIGGrftZljAOyNX9v9+ljaLRufXRFR1VkX97OXJfhWb2
FpZjOLMM0wkcuQfUBf88XjTCoxUz5Kh9E7PmPOaRczRUE/pBUFa69nJb6Crz7lI5
MDU6plsRs9mxMEAQDdboCbLRlIacMNhp0XSTM0GhEXuGK9fqD3ssmJaL+riNuW+F
QgTb2Zk8WYINK5X0BuNjujslXxiWuSPu7iqRPFoPKRZObK4ZVyCRVr3mjy2MloR8
Sbgn+owxA4JZEk9X/EIb3KzHqkawODOSHT8L0UG23OCtq1zqz+tGNWZ8q0hFRn0N
/c4e6h/MGzLM8JLHI49iADT6bIjEUmc19CfouuKacaE299ab/AW8KRsMMNewVBxg
3YvGPsn9DK1ridrn/v6W1sL4n0Ci8znuZO1nf0jnDQdmIgeX02fmzs637bNfoe7Y
Qzn9hLSu890UQTaMEhAh/Rq8M1gEc0KG+QuKfCy3P/BH57qqzmW+6JoWY22d7So1
ukvLfdiYHomJFT33ohjG6+N16suKpZJNM3RqbkLXbqwG4nDI2a3k8hwSwe2oqEIy
QUq6NtvNwd+uwln+TsISy95RkiZ/VUMhl7BvV6ZiINUN58ayJj8TtAqzYEXDxQXf
4ian4Kb1oNvlzQWzoECt
=Qpuk
-----END PGP SIGNATURE-----

**Comment by khaledJabr** [comment]
@JeremyRand  i did that last night, but the build still failed.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

MalandroKLD:
> @JeremyRand  i did that last night, but the build still failed.

Any chance you could link to the error in this thread?

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYIEt+AAoJELPy0WV4bWVwsikP/iAGeDvbIl01Enr5yXIi6Jjh
6WqYSx9EDEbErqvMuCcTd87hKcwZYKTIyc5xh7IKgjF7sZAy1Zbz7KKcB+xa0OvK
4TfUf5J6AXUVMmfIITpSTJ+td7GjZsNvrbcVWVMVpORFIO7cH3i+2d1KlSn231tV
UMumIG1hf7WbgGUqZs6km1UwKJVxpIGlqHcgNIFyGErxZc+C5EIu0GzGLfB4MD/j
/YCoPzAZ7HvgSx1dt3LFaReoXJC2glJLW8O3bDDvkfdQG7HleEjX+P1o1RwZX9Ti
3oJ6l2A4LDY5RZHYr0LPoSSK8FVNtKkJ2OkGlXbjnUwqKQl8YFdP7/g88IU1Rky7
hITtkh8bidXCiDp7W80XcW+daTxfvQwfOjNj+iMPwFBifOivGRyl4KSuy/6MSv4D
1uslprnj4ALWYUqb5L6PUuCMreCLHnQczpC50QE0CTG+B1mOiHdntMagZCrlfPGJ
7oubsRMzC4rStqG8BZhqlBaA1odSbVuWgcp4QwfkLCckCZx6Wx0oYFMc/MEY5fYK
3mcmsyTrZt0g/P6XBE/ENQ2TPhSy7RqZ3LgAG3cl87nJzdVaSYkCDDDi4/Wf788p
LvlhDYSsaKT2jb0OG4YBr39MkFs9jD7taMMskMnWMHP8AU9LoE38HWqcosdJgWs1
fOsqDTtM9UDnUSs51YTY
=7WRo
-----END PGP SIGNATURE-----

**Comment by khaledJabr** [comment]
@JeremyRand , two errors 

https://travis-ci.org/namecoin/namecoin-core/jobs/173172330#L480

https://travis-ci.org/namecoin/namecoin-core/jobs/173172330#L488

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

MalandroKLD:
> @JeremyRand , two errors
> 
> https://travis-ci.org/namecoin/namecoin-core/jobs/173172330#L480
> 
> https://travis-ci.org/namecoin/namecoin-core/jobs/173172330#L488

The first error that occurs in that log is earlier, looks like it's
this: https://travis-ci.org/namecoin/namecoin-core/jobs/173172330#L467 .

That should be fixed by my previous suggestion... it looks like in
that build job the suggestion I made isn't applied?  See
https://travis-ci.org/namecoin/namecoin-core/jobs/173172330#L393 .
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYJwUMAAoJELPy0WV4bWVwQu4QAKS5BTYT5UA5J3o/WEGh/RdP
9JO77JSdcQBC3Ir0udDWziVu1Z86fW/u+96vgGnI+avqY92G2GSCE7KnwveCkcIb
XSqtIKtRihNTfX4q6IWs7AH1iBDiDpeHdiefu2djcJZuuNZQ1t0xkVjSTUmLGxUq
U4Am5zH76012ffBSu6ddEZNpKZ0JCYoJh71/p3ISqbt1gJHMF4X8nZeRg+pEIXjQ
Ici+1KwHzX/0HppdyzwancJ4STfIyutS+HZAX9YTp24Ap1JNVwmoFEYubE5g8yX8
zfxVq7c9MZRdu604UKC3NzBAZk5jd9EKltJPEPD0TePSXJ6mIIb9kiKdiYb7mVyR
VAGDGof0fO1gVSdp8C3nuJN0l+jqxjKuqAHAH2xGdluqJkmaQxhY7mpI5O4LgW1g
KN3okCXcZruozXNKx+zvSgBKOhZ6PWzlXJIsk+kOHgmdQzVweO/Ex0uh58zZo9DW
bsoFn71v63mqfe/7qcqhEoptjUbCjzFagIhUAeCCcFjJjfL5p03ZRA7kh/rAT5Vv
Q+zfgqrY22bD23sYafA53esMM/gFBLONuFYTulkJBrZF7qoypU8QiGLrPlDColyh
6KUrbV1QGW6kEOH5HWAzbamQfXgLBEcFYn9x67iHNFi2uABvzyYk1p1ucmVJ119v
GgbjlxkKVZEyLwVRAHQv
=1fs9
-----END PGP SIGNATURE-----

**Comment by khaledJabr** [comment]
@JeremyRand Im a little lost to what are we supposed to do here, and to what do you mean by isn't applied? did i miss something?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

MalandroKLD:
> @JeremyRand Im a little lost to what are we supposed to do here, 
> and to what do you mean by isn't applied? did i miss something?

Hmm, looks like one of my previous messages got eaten by a GitHub UX
fail.  Sorry about that.

Pasting in the message that I intended to send:

"Ah cool, csbuild starts now.  My inclination to fix the current error
is just to remove "&& mkdir build && cd build " from
https://github.com/khaledJabr/namecoin-core/blob/7333ba05ba91cf40b16e6e8
9c43e6141f88532bb/.travis.yml#L77
."

Cheers.
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYLETVAAoJELPy0WV4bWVwYDEQAI9bG9qvAN5ELItY33ckPUZO
00frPIubsI2w96fZHN9A1EoqMOA6eNNfGkey/mi3KeCOkvg/O+a6B2uhKuJD6c9f
CemXNkCGRdnHu78VdZ9pSZLjqRWDGkYWaQ+nPRqZOHXO/9uqq/MpRc/6WIkIjVcD
7KQTqlNrWS+60YtQvDoix77ygeLmj2l4FwbNL5G491MKYMSN86dkddkSkmYDPwIi
ZzoD6+uIvsbWFhvr1vzl0MiACeWQYCu1wK1+C4xw1xzBe/yE3IkxPGtzZAh7LQTF
JPyHS60aWX5p63lNLr0l47imGJt44hSOq4XmPTqDQpNlqiLTYJwrk+lm/LEXZBc8
btSfwxf1YUpMZ7cJWSOwC8NEMy+t0z5OxhTk9JtUVEhKRv2t7ZOfm5UWz9WWqVZx
x2XzTTV+1kQNapfjjT4BAB9/6b0gVFhqLeePDvs63O0eXl6jjvWXQQu3ryTbEiXG
7deMNbW/yzzNZlq9qIwNYeqQPKU27JT37cbXHQ/bzL4Nt9wmvI30M0ZwWCEEg7Yc
6drg7aEZJhseO7rEefhT9fVpnIeTgCGnIJmrGnho8poG19n3pST9kM0aWJo+DiTb
l7ZCSewp1pPe/RXsIftrsLDj/mhFlT7xHn5x3PA3SYmplvUcCP4gu1dGE5Wuj+An
PQaDpuw3DLjP3/azbC5u
=/iBE
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

It looks like we're exhausting the 4 MB limit on log length that
Travis has.  I suspect that this is because csbuild is displaying
warnings for each build (Bitcoin and Namecoin).  All we really care
about is seeing the warnings that exist for Namecoin but not Bitcoin.
 I think csbuild has some command line options for configuring this...
maybe try tinkering with those?
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYLmqZAAoJELPy0WV4bWVwTEMP/RSR7hX1JybpksS2uwSTJ41N
F1eV3Ut5wTiFFdfnyg7Rr2sU2xy7JaePgJ7UZCdsRIx8Hg8du1z6jepQdMo8t3xt
bvJpNK/ngUggJcT3wsmbhZyf7jsB+4k7MzFOQgj8nT4EuSFi1WCWpHYsX1Qw6Ut7
gfV/H2rb2Q12LqJETCMiEOA8dMOlkpLjTBD/ZUHqXCOCBk3wtVCZMmqzQzhwhTZy
Z+13Dys1/gotUQ6jiKfc+g0ZSZOg+Hvs8PaNXrTHhyLvVcm8fL8PkCGNNwWeV/95
0MJTFcCalWZBgNFfn1bV0PeA7zAtR9Uxwg97ahcY43gNBD0UXJJLelJKcKpCx/KF
HOIiyT2PZZthvvqNYwFYhOQsl0YQGqHBUpK6jwqo1mxDZFd5fbqxmg7GQ7wPx86B
X5TA6JY6uJbkNZTz3Vm9T4EQCxdVmUTMFjfjZnblPXq8VU+Thq9Y29sJqkQ1GhBw
e0/aM/KtT3IG9ZiVFO1bkywUpu2lRbhPX3tqAXCLWwuQrIND5GmrANplKCd2oxlE
4DpMmMuPg+Fs+0VYjk+kEmGOu+fAUTaWiVrpLVL5Nhf+nKyV1t0iGyjTJVG7KIZs
YlqeutVcLze77SEfOtmahLY+ZqiwXTH566Zh+Xx7t4TKUOEOHagXYcJz5VbDILMv
akYLxBTpk13IHAD5wyiq
=67WY
-----END PGP SIGNATURE-----

**Comment by domob1812** [comment]
Closing this as obsolete.  Feel free to reopen if you want to take this up again.

**Pull request closed without merging**
