### PR TITLE
Build: Rebrand logo for macOS deploy

### PR DESCRIPTION
**Pull request by JeremyRand**
~~Depends on https://github.com/namecoin/namecoin-core/pull/204 (it will be ready for review once that PR is merged).~~  Refs https://github.com/namecoin/namecoin-core/issues/167 .

Note that I haven't actually tested this icon on a macOS machine, so it might be broken.

### CODE REVIEW

**Comment by JeremyRand** [comment]
@upsuper given your comment in https://github.com/namecoin/namecoin-core/pull/179#issuecomment-338625455 , would you like to test this out?

**Comment by JeremyRand** [comment]
#204 is merged, so this PR is now ready for consideration of merging.

**Comment by upsuper** [comment]
OK, I confirm that this patch works. (FWIW, since this PR includes a merge, it took me some time to figure out what to apply on the repo. It would be easier if you removed the merge and commit exists in master already.)

**Comment by JeremyRand** [comment]
Thanks @upsuper!  (Sorry for the ambiguity on the merge.)

@domob1812 Is it okay to merge this?

**Comment by domob1812** [comment]
utACK a84de15f34e83fd5494b4e5119f14fa9b6be68f0.  Feel free to merge.

**Pull request merged**
