### PR TITLE
Berkeley DB v6 compatibility fix

### PR DESCRIPTION
**Pull request by netsafe**
Fixes building error looking like this:
  CXX      wallet/libbitcoin_wallet_a-db.o
wallet/db.cpp: In member function ‘void CDBEnv::EnvShutdown()’:
wallet/db.cpp:46:16: error: call of overloaded ‘DbEnv(int)’ is ambiguous
         DbEnv(0).remove(strPath.c_str(), 0);
                ^
wallet/db.cpp:46:16: note: candidates are:
In file included from wallet/db.h:21:0,
                 from wallet/db.cpp:6:
/usr/include/db_cxx.h:916:2: note: DbEnv::DbEnv(const DbEnv&)
  DbEnv(const DbEnv &);
  ^
/usr/include/db_cxx.h:518:2: note: DbEnv::DbEnv(DB_ENV*)
  DbEnv(DB_ENV *dbenv);
  ^
/usr/include/db_cxx.h:516:2: note: DbEnv::DbEnv(u_int32_t)
  DbEnv(u_int32_t flags);
  ^
Makefile:5780: recipe for target 'wallet/libbitcoin_wallet_a-db.o' failed
make[2]: *** [wallet/libbitcoin_wallet_a-db.o] Error 1

### CODE REVIEW

**Comment by JeremyRand** [comment]
If this is a bug (I haven't tested), it looks like it affects Bitcoin
too.  See
https://github.com/namecoin/namecoin-core/blob/bitcoin/src/wallet/db.cpp#L46
.  Am I mistaken?  If it affects Bitcoin, the fix should be submitted
upstream to Bitcoin Core.

(My review is based on 6dd628f9f7fc00f8947549c1526e34b6b2e54230 .)

**Comment by netsafe** [comment]
@JeremyRand Yes, it's a bug. To reproduce it grab latest Berkeley DB v6 from Oracle, compile it and try to build namecoin-core. On Armbian:

# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10)
# uname -a
Linux orangepipc 4.6.2-sun8i #2 SMP Thu Jun 30 22:03:10 CEST 2016 armv7l GNU/Linux

To spot the bug try to compile namecoin-core and you will get this error. Add my type conversion - all builds fine, make check is passed successfully, it works.

# ldd /usr/namecoin/bin/namecoind
        linux-vdso.so.1 (0xbe986000)
        libboost_system.so.1.60.0 => /usr/lib/libboost_system.so.1.60.0 (0xb6af1000)
        libboost_filesystem.so.1.60.0 => /usr/lib/libboost_filesystem.so.1.60.0 (0xb6acf000)
        libboost_program_options.so.1.60.0 => /usr/lib/libboost_program_options.so.1.60.0 (0xb6a6e000)
        libboost_thread.so.1.60.0 => /usr/lib/libboost_thread.so.1.60.0 (0xb6a45000)
        libboost_chrono.so.1.60.0 => /usr/lib/libboost_chrono.so.1.60.0 (0xb6a30000)
        libdb_cxx-6.2.so => /usr/lib/libdb_cxx-6.2.so (0xb68d6000)
        libssl.so.1.0.0 => /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.0 (0xb688c000)
        libcrypto.so.1.0.0 => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0 (0xb6766000)
        libevent_pthreads-2.0.so.5 => /usr/lib/arm-linux-gnueabihf/libevent_pthreads-2.0.so.5 (0xb6754000)
        libevent-2.0.so.5 => /usr/lib/arm-linux-gnueabihf/libevent-2.0.so.5 (0xb6716000)
        libanl.so.1 => /lib/arm-linux-gnueabihf/libanl.so.1 (0xb6702000)
        libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0xb664a000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb65d6000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb65ad000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb658a000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb649a000)
        /lib/ld-linux-armhf.so.3 (0x7f64b000)
        librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0xb6483000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb6470000)
        libevent_core-2.0.so.5 => /usr/lib/arm-linux-gnueabihf/libevent_core-2.0.so.5 (0xb6443000)

Kernel and gcc 4.9 are standard from official repo. Posted a pull request to bitcoin as well.

**Comment by JeremyRand** [comment]
@netsafe Thanks for submitting upstream.  I'll leave this issue open
until the Bitcoin Core devs decide whether to merge.  If they merge your
PR, we will presumably merge it from Bitcoin Core.

Cheers!

**Comment by netsafe** [comment]
@JeremyRand It was accepted by bitcoin, you can safely merge it too

**Comment by domob1812** [comment]
@netsafe Thanks!  It is not about merging safely, but about being as close to upstream Bitcoin as possible (with the necessary changes for Namecoin), just for practical reasons and easy maintainability.  We'll merge the patch with the regular upstream merges I do, probably in one and a half weeks (when I'm back from travel).

**Pull request closed without merging**
