### PR TITLE
Build: macOS: Rebrand filenames.

### PR DESCRIPTION
**Pull request by JeremyRand**
Refs #167 

I can't test this PR since I no longer have access to the OU lab with the macOS machine.

### CODE REVIEW

**Comment by JeremyRand** [comment]
@jloughry any chance you'd be interested in testing this?

**Comment by jloughry** [comment]
Sure! I'll test it.

Thanks,
Joe

**Comment by jloughry** [comment]
Problem Report
---------------

I tested pull request #179  but encountered a problem at the `make deploy` step. The error message was:

````
919:989: execution error: Finder got an error: Can’t set item "Bitcoin-Qt.app" of Finder window id 3918 to {128, 156}. (-10006)
Error running osascript.
+ Finalizing .dmg disk image +
hdiutil: convert failed - Resource temporarily unavailable
make: *** [Namecoin-Core.dmg] Error 1
````

How to reproduce it
--------------------

1. git clone https://github.com/namecoin/namecoin-core.git
2. cd namecoin-core
3. git pull origin pull/179/head
4. ./autogen.sh
5. ./configure
6. make
7. make check
8. Make deploy

I can drag the newly created app into the Applications folder but it appears with a slashed circle over its icon; if I try to run it, Finder says 'You can’t open the application “Namecoin-Qt.app” because it may be damaged or incomplete.'

Workaround
------------

If I delete the line from the AppleScript file `namecoin-core/contrib/macdeploy/macdeployqtplus` that tries to move the icon to {128, 156} then the AppleScript runs to completion and the `make deploy` seems to work. It ends up saying:

````
+ Finalizing .dmg disk image +
Preparing imaging engine…
Reading Protective Master Boot Record (MBR : 0)…
   (CRC32 $51EEDA2C: Protective Master Boot Record (MBR : 0))
Reading GPT Header (Primary GPT Header : 1)…
   (CRC32 $1A728EF0: GPT Header (Primary GPT Header : 1))
Reading GPT Partition Data (Primary GPT Table : 2)…
   (CRC32 $38CB708A: GPT Partition Data (Primary GPT Table : 2))
Reading  (Apple_Free : 3)…
   (CRC32 $00000000:  (Apple_Free : 3))
Reading disk image (Apple_HFS : 4)…
...................................................................................................
   (CRC32 $B020C43D: disk image (Apple_HFS : 4))
Reading  (Apple_Free : 5)…
...................................................................................................
   (CRC32 $00000000:  (Apple_Free : 5))
Reading GPT Partition Data (Backup GPT Table : 6)…
...................................................................................................
   (CRC32 $38CB708A: GPT Partition Data (Backup GPT Table : 6))
Reading GPT Header (Backup GPT Header : 7)…
....................................................................................................
   (CRC32 $38EA91EB: GPT Header (Backup GPT Header : 7))
Adding resources…
....................................................................................................
Elapsed Time:  5.012s
File size: 24517095 bytes, Checksum: CRC32 $94F1D43C
Sectors processed: 150912, 136812 compressed
Speed: 13.3Mbytes/sec
Savings: 68.3%
created: /Users/rjl/thesis/github/namecoin-core/Namecoin-Qt.dmg
+ Done +
````

But the new application icon in the .dmg file still appears with a slashed circle superimposed on it and Finder still says 'You can’t open the application “Namecoin-Qt.app” because it may be damaged or incomplete.'

Additional Notes
-----------------

When the AppleScript doesn't complete, it leaves the .dmg file mounted, and the next time you run `make deploy` you get a slightly different error message:

````
631:709: execution error: Finder got an error: Can’t set file ".background:background.tiff" of disk "Namecoin-Core" to file ".background:background.tiff" of disk "Namecoin-Core". (-10006)
Error running osascript.
+ Finalizing .dmg disk image +
hdiutil: convert failed - Resource temporarily unavailable
make: *** [Namecoin-Core.dmg] Error 1
````

**Comment by jloughry** [comment]
**Summary: the pull request tests OK and ought to be merged.**

I forgot to address the actual pull request, sorry. It works; the Namecoin icon appears everywhere it should, on the app in the Dock when it's running (tooltip when the cursor hovers over the icon says Namecoin-Qt as it should), on the About screen in the app, and when Command-tab switching among applications. I am able to run the app if I dig into the Contents of Namecoin-Qt.app in the broken .dmg file; it's only the process `make deploy` that's broken right now.

It's connecting to the network and running great.

*Question: how should I communicate this back to whomever has the power to merge the pull request? Is a comment here enough or is there a better way to tell someone?*

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hmm, the `make deploy` errors don't sound good.  I'll look into it.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZjXgqAAoJELPy0WV4bWVwtSMQANTi8Qb/+80sIqp3RWKGzBUF
2xfKM6d9cynrAYVuv+gTEU2PnNsXu+OEDpiak9Jgx+kI7/8Ope69VCoLHOZbbFE9
H8+RhrOw6rAQQEGp5rytY1c10mX3Sz9tgul4etKWeeXzndI9xUBw9COfsJOcD3Cz
qGfRbH59x1h3yU7+NUFN6nbXUJPQem1rWXhWDXor23g9p3n+CxfNf00TfaD8ETuC
qoQo1zuhzniNSD6Sffrr1s4sCx0k29WoAYjyHMOx1tUhgf5cAsiM9L2kPapOVpve
HLa+PNS4lOySP8v6cFJjLB/4+WqRCHTFR0h8DBxbkxZN+JQJ3IKtNQ6MTCL5Gg/K
kLFgpWjrpaVynr0YkBe1WVjkL4KGUc0KgmQHkBwE/gwDuCMYX1qUPm3F+nuggWq+
TC3rQT0SEMIPIaP7ZFubgOWv5xkY93DvGFAsL5G+Fe+dmXHzm72lDGq3FRKrakyi
MflyRtl1IkUJRDtdyChvmqVM/pwtYGwlgoAE6PuaPTruuMe5WikYNk1my1WhIizu
uHHor8spBlgd/RG9WQGDsHzNim6727aAXDZa1QkWE7joafHC/iKqD5wEYBpXSYtc
o0FJupFbUATAuasYwxK1/SjuSyJmxIbRtlEUL5PA+Q340QTN5NjhynmnY5JUCfsW
Sx5DifWgu0rHQr66HKeH
=6MkH
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
Grep to the rescue -- I think the changes in ab18e1def477af416c0fb004e72c4e09dd3b5b0c are likely to improve things.  @jloughry can you see whether `make deploy` works any better this time?

> I wish it said Namecoin Core on the tooltip when the cursor hovers over the icon in the Dock, but that's addressable simply by renaming the executable file inside Namecoin-Qt.app.

What is the current name of the executable file, and what should it be changed to?

Cheers.

**Comment by JeremyRand** [comment]
@jloughry By the way, when reviewing a PR, please include the commit hash that you tested with; this makes it easier to keep track of what's been reviewed when PR's get rebased.

(Note to Namecoin Core devs -- I'd like to squash this PR prior to merging, so please don't merge yet.)

**Comment by upsuper** [comment]
This doesn't seem to work for me. With this patch, the system says that "You can't open the application Namecoin-Qt because it may be damaged or incomplete."

It works fine when this patch is not applied (though the filename is Bitcoint-Qt).

**Comment by JeremyRand** [comment]
@upsuper:

> This doesn't seem to work for me. With this patch, the system says that "You can't open the application Namecoin-Qt because it may be damaged or incomplete."
> 
> It works fine when this patch is not applied (though the filename is Bitcoint-Qt).

I was afraid of that.  This is going to be tricky to debug without more information on what macOS thinks is damaged.  Would you by any chance be able to upload a copy of the broken binary somewhere, so that I (or anyone else who wants to) can try to do some analysis on it?

**Comment by JeremyRand** [comment]
Actually I think I found the issue.  Possible fix incoming shortly.

**Comment by JeremyRand** [comment]
Okay, so hopefully this will fix the error that @upsuper reported.  It should also fix the package reporting itself as Bitcoin-Qt in a few pieces of metadata.  It should also fix payment requests (it was previously associating itself with Bitcoin payment requests, which obviously is a bad thing).

@upsuper can you try again (assuming that the Travis CI build passes)?  Also please make sure you mention what commit hash you've tested against.  Thanks!

**Comment by upsuper** [comment]
Yep, with the latest patches, the application can be opened normally now.

There is still one minor issue, though, that the icon of application is still Bitcoin. You may want to change it to Namecoin.

**Comment by JeremyRand** [comment]
Noting for the record that the Travis failure looks at first glance to be due to a bug in master branch, not anything in this PR.

> There is still one minor issue, though, that the icon of application is still Bitcoin. You may want to change it to Namecoin.

Yes, that is out of scope for this PR, and is a known issue.  Shouldn't be hard to fix, will look into it.

@domob1812 can you give this a quick sanity check for anything that's an obvious NACK, and if you're satisfied please merge?

**Comment by JeremyRand** [comment]
@domob1812 Reminder to look at this.

**Comment by domob1812** [comment]
Looks good (in the future, please squash commits for something simple like this).  Merging.

**Comment by JeremyRand** [comment]
(Actually I would have been happy to squash on request prior to merging.  I prefer not to squash while review is ongoing since it makes it difficult to keep track of which commits were reviewed and which weren't.)

**Pull request merged**
