### PR TITLE
Rename Bitcoin to Namecoin

### PR DESCRIPTION
**Pull request by fsb4000**
fix https://github.com/namecoin/namecoin-core/issues/55
namecoin_tx
namecoind
namecoin-cli
test_namecoin
bench_namecoin
test_namecoin-qt

### CODE REVIEW

**Comment by domob1812** [comment]
To be honest, I'm a bit skeptical about renaming files that seem not necessary to rename, like the tests and bench file.  I see no real benefit (except for it being "nicer"), and it may cause more merge conflicts in the future.  But I think general consensus was to rename those as well, so thanks for your patch - ACK.

@JeremyRand, so you think we need also changes to the Gitian descriptor to run the renamed test file (for instance)?

**Comment by JeremyRand** [comment]
Renaming the test and bench executables is, in my opinion, useful because
Bitcoin's Gitian scripts include those files in the .zip archives that we
ship to end users, i.e. they are to some extent "user-facing".  IMO
renaming "bitcoin" to "namecoin" is much better than fiddling with what
files get shipped by the Gitian scripts.  So, I concept-ACK this pull
request.

My familiarity with the Bitcoin Core makefiles is not sufficient to be
certain that the changes in this PR are as minimal as possible in order to
change the output executable filenames/metadata.  For example, I don't know
if it would be simpler or more complex to leave the .o files as "bitcoin".
My guess, looking through the code, is that this PR is about as simple as
possible (which is good).  But @domob1812 will know better than I do.

grepping the Gitian descriptors (for all 3 OS's) doesn't yield anything
obvious for either "test" or "check"; I think these are handled elsewhere
rather than in the descriptor itself.  It is entirely possible that this PR
will build in Gitian verbatim; it's also entirely possible that it will
need changes.  My machine with Gitian is down for repairs, so I can't
easily check this today.  If you need a test report soon, we have at least
3 other devs who can do Gitian builds (Joseph, Jonas, Midnight), so I can
ask one of them to check it -- let me know if you'd like me to check with
them.

**Comment by fsb4000** [comment]
I know not much about makefiles. Usually I use IDEs which autogenerate makefiles. So maybe the PR can be simplified.

**Comment by domob1812** [comment]
I think the commit is fine with respect to the autotools-changes, hence my ACK above.  @phelixbtc or someone else, can you maybe also check that everything builds fine on Windows?

**Comment by phelixbtc** [comment]
Compiles on Windows. ACK

**Comment by domob1812** [comment]
Merging, thanks for the patch!  Should we also merge this to 0.12?

**Comment by JeremyRand** [comment]
@domob1812 I'd like to see this backported to 0.12 branch as well, as long as it's not too invasive.  What does everyone else think?

**Comment by phelixbtc** [comment]
What @JeremyRand says.

**Comment by domob1812** [comment]
This is also my opinion, thus I've pushed the patch also to 0.12.

**Pull request merged**
