### PR TITLE
Docs: Update default ports in REST API documentation

### PR DESCRIPTION
**Pull request by llopv**
The new ports are 8336 and 18336, instead of 8332 and 18332 used before.

### CODE REVIEW

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK a3c294892323139ff7775860ad48ade82b41f23b

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZhyTpAAoJELPy0WV4bWVwrocP/2N0ZkcpzgEmZ4j4CAHIu/Du
wGoVo6EofMtAJQBDbMKn8DLNJv+vgvFt4OyLOmBkq2k4FB90i9I7dgZlQLhssCr2
voeOKcVXH7lPY0PcMrHgzeJ9FYM+kVOTGPyTDF+w9T0c9P9PlCtK6XRy3VEfylgg
5L1yCfhmnNqEgI6xTYP5Li68vUQap2xo8sh9LUVbNxPE//+vs/CIl79j/fnoQThN
SDRgC4u5iA7jYzGSpgs+pdFzFVVRWikDTsS+vGDDHqnYdCTG1BAJIM6E8ewir7Ke
uv3jsaPumCC1/gGD5LnW+figSdWXb9K1Qgk0gP/ZCMQaz5Dc0tqYOhsZYZR+HYm2
KZNQocFjttB0AyMK4UxqNvbpXDNWaQ0kuJyml1K7fZv1dUTvOU4hRQ5y1oRpmu0v
xc3Y8wOgSWn3Il4xW7XaV+XxadwNyJkjMc8bCiNgvltk61mtDrSwkUJlzHG33KTe
1MY7StyKrteTQ5/g5v6aI5uoRI1EYwn3ZC+CiTY1kCquwBXetrTOKSimYU2CbuiT
Pr+DI91YoVw/G60Wb8JUUz/GPfqZ4agoDU0e72j326yf2OFwhytq/VgP/T5JanIQ
U2auObS0khnVr2VREPFWCtOhLicPZ7KQDNQt9JUdxp0zEav0iYUZkDudzzCyEAeh
eIZEopTnqPhLXd3NnDSE
=98wk
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
Fixed the merge conflict.

**Comment by JeremyRand** [comment]
ACK 065181f966bf05845b18ea70f81e68ff198c0aa2 .  @domob1812 does this look okay to you?

**Comment by domob1812** [comment]
Indeed, ACK 065181f966bf05845b18ea70f81e68ff198c0aa2.  Merging.

**Pull request merged**
