### PR TITLE
Build: Rebrand NSIS images

### PR DESCRIPTION
**Pull request by JeremyRand**
New version of  #136, submitted against master branch.

### CODE REVIEW

**Comment by domob1812** [comment]
Thanks for recreating!  ACK c657e233425db4a093d7aebbb510f58758478bfa.  I'll merge this in a few days if noone else NACKs.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Daniel Kraft:
> Thanks for recreating!  ACK
> c657e233425db4a093d7aebbb510f58758478bfa.  I'll merge this in a few
> days if noone else NACKs.

Temporary NACK as I'd like to test all the images that aren't
renderable in GitHub's web UI.  I should get to it in the next couple
days, please remind me if I haven't reviewed in a week.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZECORAAoJELPy0WV4bWVwhLYQAJODtZ4DVPNS/s+Oh3mrANno
XwaQDva+ZpQ3PMBAWgHlvKqGmqTcxJgHYesJYkq281vi8RHtXbl5WSToYkqpCx1a
VzSBHYyonjssknfM60QzQ4nAIx75uTLkeBQa49gfxtEW9pvKv0wmym6S6lxELoQR
0BFdh5ggR3U5N6b/8LXLRVL5Dw42Y0gALGo2mlm3fw3wGRltHE3rIH0rCWsgoiJU
B0nky3MofCI28rnFTxdVspZdCelzWpeiQ7P1eEbZgZkWGjwPXADR5pPvgvTJIp9k
EarSVajuyWQIIjMBbNIWp9uWEh3DFRg9P4yD0zJBI+A1pYj7O1ir1Pl+irOcg8Tn
U/bMa433FSg0n0xhopODzBH8QxkpNNvetHGzwqP7Mo0nFDSsc5MC8Ap6oUeeWuKN
/mKvjnsCr+tOBmXEK81QmsB2zblrZoXUk8Dg6zjTA0o39QN6iiMlbJmj8t4Ka1Wm
95aCksiZB7bhaas0P0FISjC0yK401qe0Y/7HXe1mal4wcVfCmWzQGis1KvMNB5D7
f3ixMKy4/DOWYPd31uIUzAWKh+lcbUKIly8yphzVm6G2xqKVzjSH0ZMRw0YNq+MA
aQ/a7SOMN98LW/iKtRAVlKs4n8muM2P8rVmP0J/6GUcw8T2zOpDfLyygE7ZghSPc
N6CEEZY3IxjpH9FGr8gZ
=dDvd
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK on all the images except for nsis-header.bmp .  The new
nsis-header.bmp in this PR is very low quality and the wrong font; it
should be based on this file:

https://github.com/namecoin/namecoin-graphics/blob/master/svg/namecoin-b
anner.svg

NACK until that file is fixed -- @fsb4000 any chance you'd be able to
fix nsis-header.bmp for us?

Cheers!

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZECmGAAoJELPy0WV4bWVwqyoP/21/i9ntX1iVNFRE7iOrRKRV
g+A98E2/yrvRsArZNT/8itbv52tGGKV0XJDuc7qT+FeuqxT7IAvGh2ruScEQQfzK
qQWKGOttffCJRxCi2xc3d7jMqQxuH9ptzXqCrJgnULwTlhiBn4cwSvxQeF1fK8GJ
XXQK8a/0wDgjRSDMW+9sbn6AeqFx8zmX5nwYj5C3iIwM5B05c6DBImDYUKbVrAxZ
jhLQL6pgPqE0ZicpaVGlwqdsl5Je5USwOmGZVNCPgKZHgv+gMBw//yvLu4bxO8v4
YU5rqZgJBLNDCEspBqHkmfGOScVzNtEOGVB4FAtsaLiuyTebaI5s846yA+QuZgmB
whoR8hjc/7ertJW20RyvYDdf9MNQVdmoBXK0gjveRI5sT78y+khHxpd70BegXhnY
FQ5S/fnW9u1jwCthNDZBq51mfEsW28y0VCcWyEW1Hk//TOm+iFNkyXHVtR1lkY2y
RtC2Qx27uboPZsTWa00Tee2IT4gnsrPbofe6O9uJX9TgbOfHd4sWb11ox5HGSWO0
OeYe3/0r6zyAQaKuoPTXtIHpxB8oukMIYQvWDySBES1EnJIpwhMQf6ZHNca90MOy
uVEBuoVw3UvmDcf6jiy0MiUwEtwNGPEKTLihlnfE5d7QdVt4ApbB3RBevWdg9FlJ
cS0iYkw+dao+wJwNOe2Y
=IfCx
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
@fsb4000 any chance you'd be able to fix the merge conflicts and fix the nsis-header.bmp to be based on namecoin-banner.svg?  Thanks!

**Comment by JeremyRand** [comment]
Closing in favor of https://github.com/namecoin/namecoin-core/pull/204

**Pull request closed without merging**
