### PR TITLE
New onion address

### PR DESCRIPTION
**Pull request by redblade7**
Hi,

My seed now has an onion address: s5pknqnnt4qji33p.onion:8334

I have been testing it and working with Jeremy on IRC, and it works properly with incoming IPv4 and onion connections through the Tor proxy. The onion address only includes port 8334 (there is no web server or anything else).

I am not adding its IPv6 address to this list as I have no way of testing it from home.

Thank you!

### CODE REVIEW

**Comment by domob1812** [comment]
I think you need to run `contrib/seeds/generate-seeds.py` to regenerate `src/chainparamsseeds.h` as well.  Otherwise looks good to me - but since you've worked with Jeremy on IRC, please @JeremyRand ACK before I merge.

**Comment by redblade7** [comment]
Would you mind just adding the one line in, rather than worrying about pulling this onto my computer and running scripts?

**Comment by redblade7** [comment]
Would you mind just adding the one line in, rather than worrying about pulling this onto my computer and running scripts? Or would it be the same amount of work for you?

**Comment by redblade7** [comment]
Honestly I have no idea how this fork wound up in my account. Only the source code of the latest release is on my computer, used to compile Linux binaries.

**Comment by JeremyRand** [comment]
Generally, either @domob1812 or I will refetch the seed node list from Peter Conrad's DNS seed before the next release.  The onion seed nodes are only handled explicitly because Peter's DNS seed (for uninvestigated reasons) doesn't report them.  I don't see any reason for someone besides Daniel and me to run those scripts, so I don't think running them is a prereq for this PR being merged.

(I haven't yet reviewed this PR, and I haven't yet tried to connect to the node listed.)

**Comment by JeremyRand** [comment]
Concept ACK; I confirm that the listed onion service works properly with Namecoin Core.

> I think you need to run contrib/seeds/generate-seeds.py to regenerate src/chainparamsseeds.h as well. Otherwise looks good to me - but since you've worked with Jeremy on IRC, please @JeremyRand ACK before I merge.

I'll look into running the needed scripts and pushing the result to @redblade7 's PR branch before merging this PR.

**Comment by JeremyRand** [comment]
utACK 51090c78fec6634686618b3e00083aa16a06f892

**Comment by domob1812** [comment]
ACK 51090c78fec6634686618b3e00083aa16a06f892.

**Comment by redblade7** [comment]
Hi,

I mentioned over IRC not too long ago that I had set up an additional seed at namecoinseed2.bit/69.164.215.115/2600:3c03::f03c:91ff:fecb:f611/sexm3j23pktix43d.onion. This second seed has been shut down permanently.  (I don't think it was ever submitted to the official list, and I don't see any evidence of me or someone else mentioning this second seed on Github anywhere.)

**Pull request merged**
