### PR TITLE
Innosetup installer script

### PR DESCRIPTION
**Pull request by phelixbtc**

### CODE REVIEW

**Comment by JeremyRand** [comment]
I'm pretty sure Namecoin Core (like Bitcoin Core) already builds a
Windows installer (using reproducible NSIS).  Am I incorrect?

**Comment by phelixbtc** [comment]
The current Windows early release was done with Innosetup so it should be available to the public. Particularly so as long as there is no NSIS release available.

**Comment by JeremyRand** [comment]
The InnoSetup release was not official, so I think it can stay in your repo.  If you really want it in the official repo for visibility's sake, make it a separate branch so that we don't merge it into master, and then remove the branch from the official repo when we have an NSIS release.  (As an aside, I recently fixed my Gitian installation, so I might make a Gitian Windows release sometime soon.)  I definitely NACK merging an InnoSetup script into the official repo when the official repo already has NSIS.

**Comment by JeremyRand** [comment]
This is just a note that Gitian NSIS fixes were merged to the 0.12 branch recently.  master branch is still waiting for some upstream fixes.  In any event, looks like we don't need the InnoSetup script at this point.  (Although it'd be great if someone else can test my Gitian script and make sure it works for them too.)

**Comment by JeremyRand** [comment]
Closing since NSIS is working fine now.

**Pull request closed without merging**
