### PR TITLE
Correcting the instance where the prior opcode is a OP_NAME*, but the

### PR DESCRIPTION
**Pull request by JeremyRand**
New version of #141 , submitted to the master branch.

### CODE REVIEW

**Comment by domob1812** [comment]
ACK 90de1e426ce2d582320bf3b0846bc987e1c18e31.  I'll merge in a couple of days unless someone NACKs.

**Comment by JeremyRand** [comment]
@midnightmagic Any chance you could rebase this to solve the merge conflicts?

**Comment by midnightmagic** [comment]
Oh, do I need to rebase this still? I thought the idea was to wait until domob was finished with something else which may have conflicted it. Is it time for me to fix it now?

**Comment by domob1812** [comment]
Sorry for forgetting about this!  If you don't mind, please rebase yourself, then I can merge from the UI and thus keep the "paper trail" clean.  But if you prefer me to rebase and merge directly from my client, let me know and I can do that instead.

**Comment by domob1812** [comment]
I've rebased and squashed this, new pull request is in #230.

**Pull request closed without merging**
