### PR TITLE
Schedule segwit activation softfork.

### PR DESCRIPTION
**Pull request by domob1812**
This schedules a softfork activating BIP16 (P2SH), Segwit and CSV at a future blockheight on mainnet and testnet.

On mainnet, the activation will happen at block **475,000**, which is expected to be mined in about half a year.  On testnet, the activation happens at block 232,000, or in one to two weeks (but depending strongly on the mining activity on testnet).

See #239 for a discussion, including the commitment to update timely by many of the most important
mining pools.

### CODE REVIEW

**Comment by domob1812** [comment]
@JeremyRand and others, please take a look and confirm this is good for you.  After I get that confirmation, I will merge this to `master`, backport to the `0.18` branch, and then release `0.18.0` based on Bitcoin Core 0.18.0.

**Comment by domob1812** [comment]
For reference, the current mainnet height is 450,207 and the testnet height is 229,299.

**Comment by domob1812** [comment]
@JeremyRand, please take a look at this.  I'd like to get this merged soon so we can release 0.18.0 and get everyone to update for the fork as soon as possible.  But I do not want to merge this change without any ACKs.

**Comment by JeremyRand** [comment]
Sorry for the delay, looking at it now.

**Comment by JeremyRand** [comment]
@domob1812 Just to verify, the only thing I'm supposed to review is the fork heights, right?  AFAICT that's the only substantive thing in this PR.  Or are you asking me to also review the implementations of P2SH/CSV/SegWit that were added previously (but were inactive as long as the fork wasn't activated)?

**Comment by JeremyRand** [comment]
Mainnet height of 475000 should (assuming 10-minute block time) activate in about 5.5 months; ACK on that.

I'd prefer targeting testnet at 1 month in the future rather than 1-2 weeks, but wrecking testnet and causing a big re-org there isn't exactly a disaster, so I'm not going to block this PR based on the testnet height.

@domob1812  Let me know if there's anything else you need me to review.

**Comment by domob1812** [comment]
@JeremyRand, thanks!  Yes, I just want your confirmation that the heights are fine (and the general intent, but we discussed that already anyway).

I have no idea how frequent testnet blocks are, and I thought that people might not actually mine it regularly - that's why I think an earlier block height is better than a later one, which might perhaps only be hit much later than planned.  But if you think you have a good estimate on mining activity and want to suggest a height, I'm happy to put there whatever you want.

**Comment by JeremyRand** [comment]
> I have no idea how frequent testnet blocks are, and I thought that people might not actually mine it regularly - that's why I think an earlier block height is better than a later one, which might perhaps only be hit much later than planned. But if you think you have a good estimate on mining activity and want to suggest a height, I'm happy to put there whatever you want.

I don't use testnet myself (typically I only use mainnet and regtest), and if anyone regularly mines testnet, I'm not aware of it.  So yeah, your height is probably fine; I don't have any useful info on how much mining happens there.

**Comment by domob1812** [comment]
Ok.  I just checked again, and testnet is at the moment at 229,310.  So there were 11 blocks in the last week - I think the height is definitely not too early, unless someone starts mining massively now without updating first.

Then I'll merge this, backport to 0.18 and release 0.18.0 after today's upstream patches for master.

**Comment by domob1812** [comment]
Backported to 0.18 as 9d3e3cf8fc04535552e034f92d27d23b9a5c4d48.

**Pull request merged**
